-- MySQL Script generated by MySQL Workbench
-- Mon Mar 20 20:12:11 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_otk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_otk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_otk` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_otk` ;

-- -----------------------------------------------------
-- Table `db_otk`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_otk`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `FIO` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idusers_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_otk`.`personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_otk`.`personal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(17) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `FIO` VARCHAR(45) NOT NULL,
  `avatar` BLOB NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_otk`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_otk`.`service` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_service` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_otk`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_otk`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `id_container` INT NOT NULL,
  `users_id` INT NOT NULL,
  `personal_id` INT NOT NULL,
  `service_id` INT NOT NULL,
  PRIMARY KEY (`id`, `personal_id`, `service_id`, `users_id`),
  UNIQUE INDEX `idorders_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_orders_users_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_orders_personal1_idx` (`personal_id` ASC) VISIBLE,
  INDEX `fk_orders_service1_idx` (`service_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `db_otk`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_personal1`
    FOREIGN KEY (`personal_id`)
    REFERENCES `db_otk`.`personal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_service1`
    FOREIGN KEY (`service_id`)
    REFERENCES `db_otk`.`service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
